apiVersion: batch/v1
kind: Job
metadata:
  name: zos
spec:
  completions: 8
  parallelism: 1
  template:
    metadata:
      name: zos
    spec:
      containers:
      - name: c
        image: dknoern/zos-worker
        env:
        - name: BROKER_URL
          value: amqp://guest:guest@rabbitmq-service:5672
        - name: QUEUE
          value: job1
        volumeMounts:
        - name: mypd
          mountPath: "/var/lib/jobs"
      volumes:
      - name: mypd
        persistentVolumeClaim:
          claimName: myclaim  
      restartPolicy: OnFailure
